/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    `java-library`
    `maven-publish`
    signing
    distribution
}

group = "io.github.algafix"
version = "0.2"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly(libs.junit.platform)

    // This dependency is used by the application.
    implementation(libs.guava)

    // Aleix
    implementation(libs.commons.net)
    implementation(libs.conscrypt)
    implementation(libs.tink)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withJavadocJar()
    withSourcesJar()
}

application {
    // Define the main class for the application.
    mainClass = "NTSTime"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

publishing{
    publications {
        create<MavenPublication>("mavenJava"){
            artifactId = "JavaNTSClient"
            from(components["java"])
            versionMapping{
                usage("java-api"){
                    fromResolutionOf("runtimeClasspath")
                }
                usage("java-runtime"){
                    fromResolutionResult()
                }
            }
            pom {
                name = "Java NTS Client"
                description = "A Simple NTP client with Network Time Security (NTS) capability"
                url = "https://www.github.com/algafix/JavaNTSClient"
                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }
                developers {
                    developer {
                        id = "algafix"
                        name = "Aleix Galan"
                    }
                }
                scm {
                    connection = "scm:git:git://www.github.com/algafix/JavaNTSClient.git"

                }
            }
        }
    }
}

//signing {
//    sign(publishing.publications["mavenJava"])
//}
