/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("application")
    // Apply the java-library plugin to add support for api configuration.
    id("java-library")
    id("com.vanniktech.maven.publish") version "0.35.0"
}

group = "io.github.algafix"
version = "1.0.1"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly(libs.junit.platform)

    // This dependency is used by the application.
    implementation(libs.guava)

    // Aleix
    api(libs.commons.net)
    implementation(libs.conscrypt)
    implementation(libs.tink)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "NTSTime"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    // Exclude all tests or make tests optional (we are not defining any @Test in the test classes)
    filter {
        failOnNoDiscoveredTests = false
    }
}

mavenPublishing {
    coordinates("io.github.algafix", "JavaNTSClient", version.toString())
    pom {
        name.set("Java NTS Client")
        description.set("A Simple NTP client with Network Time Security (NTS) capability")
        url.set("https://www.github.com/algafix/JavaNTSClient")
        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                distribution.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                id.set("algafix")
                name.set("Aleix Galan")
                url.set("https://www.github.com/algafix")
            }
            developer {
                id.set("odrisci")
                name.set("Cillian O'Driscoll")
                url.set("https://github.com/odrisci")
            }
        }
        scm {
            url.set("https://www.github.com/algafix/JavaNTSClient")
            connection.set("scm:git:git://www.github.com/algafix/JavaNTSClient.git")
            developerConnection.set("scm:git:ssh://www.github.com/algafix/JavaNTSClient.git")
        }
    }
}


